import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillInstagram,
  AiFillGithub,
} from "react-icons/ai";

import Image from "next/image";
import francis from "../public/francis.jpg";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Iwu Francis's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Developed by Francis</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-5"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Francis Iwu
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Engineer and Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">
              Engineer at construction and a full stack web developer. Join me
              down below and let's get it up and running
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillGithub />
            <AiFillLinkedin />
            <AiFillInstagram />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={francis} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">About me</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Hello, I'm Francis Iwu, a passionate full-stack web developer with
              a focus on creating user-friendly and visually appealing web
              applications. I am excited about the intersection of technology
              and creativity, and I strive to deliver high-quality solutions
              that enhance the user experience. With a solid foundation in
              front-end and back-end technologies, I enjoy working on diverse
              projects that challenge me to learn and grow as a developer.
            </p>

            <p className="text-md py-2 leading-8 text-gray-800">
              I am skilled in HTML5, CSS3, Tailwindcss, JavaScript, React,
              Node.js, Handlebars and more. My ability to collaborate
              effectively in team environments and my attention to detail are
              key strengths that contribute to successful project outcomes.I am
              a recent graduate of a full stack web development bootcamp, where
              I honed my skills and gained hands-on experience building
              responsive and dynamic web applications. I am constantly exploring
              new technologies and staying up to date with the latest industry
              trends to ensure that I deliver modern and efficient solutions.
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful designs
              </h3>
              <p className="py-2">
                With a solid foundation in front-end and back-end technologies,
                I enjoy working on diverse projects that challenge me to learn
                and grow as a developer.
              </p>
              <h4 className="py-4 text-teal-600 ">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful designs
              </h3>
              <p className="py-2">
                With a solid foundation in front-end and back-end technologies,
                I enjoy working on diverse projects that challenge me to learn
                and grow as a developer.
              </p>
              <h4 className="py-4 text-teal-600 ">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful designs
              </h3>
              <p className="py-2">
                With a solid foundation in front-end and back-end technologies,
                I enjoy working on diverse projects that challenge me to learn
                and grow as a developer.
              </p>
              <h4 className="py-4 text-teal-600 ">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              {" "}
              With a solid foundation in front-end and back-end technologies, I
              enjoy working on diverse projects that challenge me to learn and
              grow as a developer.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
